default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: beacon_tracker_api_development
test:
  <<: *default
  database: beacon_tracker_api_test

production:
  <<: *default
  database: beacon_tracker_api_production
