# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b065df652f45e10dab23eaa9760544e9ee678a619db6272a365268cf9730c57cbdd875ba4a5067f852d17fdc6aa5650bf294b0ac3e56eb3e360199bb394886

test:
  secret_key_base: 00b8a47d2e46c2ce1a61cba4fa8d9a3e4956d28b7c7a3d1fbed3fe6cdf77d1f576b1e043e026b0c5e6f7ce52bd5f8a82078f03ee3ae5d62eafc7ea347da2f244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
